name: Build and Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Gradle
      run: |
        cd kakao
        ./gradlew build

    - name: Grant execute permission to Gradle wrapper
      run: |
        chmod +x kakao/gradlew

    - name: Archive Gradle artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-artifact
        path: kakao/build/libs/*.jar

    - name: Build Docker image
      run: docker build kakao --file kakao/Dockerfile --tag realcommang/springprac:$(date +%s)
